"""Recompute current result evidence without fitting or selecting a model."""
from pathlib import Path
import json,hashlib
import pandas as pd
import numpy as np
ROOT=Path(__file__).resolve().parent;OUT=ROOT/'resumed_completion_audit';OUT.mkdir(exist_ok=True)
truth=pd.read_csv(ROOT/'delayed_probe/later_results.csv')[['pid','day','actual']].sort_values(['pid','day']);keys=['pid','day'];rows=[]
manifest={'later_results.csv':['prediction'],'context_probe/later_results.csv':['prediction'],'delayed_probe/later_results.csv':['delayed'],'personal_daily/later_results.csv':['prediction'],'shared_daily/later_results.csv':['prediction'],'crossfit_daily/later_results.csv':['prediction'],'pair_change/later_results.csv':['prediction'],'excursion_probe/later_results.csv':['prediction'],'full_pool_validation/later_results.csv':['prediction'],'phenotype_probe/later_results.csv':['none','basic','labs'],'ensemble_probe/later_results.csv':['ensemble','uniform'],'timing_probe/later_results.csv':['shifted_prediction'],'percentage_loss_probe/later_results.csv':['prediction'],'warped_daily_probe/later_results.csv':['prediction'],'multiscale_daily_probe/later_results.csv':['prediction'],'tea_day_sensitivity/later_results.csv':['added_day'],'robust_ensemble_probe/later_results.csv':['prediction'],'hourly_probe/later_results.csv':['prediction'],'composition_diagnostic/later_results.csv':['sensors','known_composition','combined'],'event_activity_probe/daily_predictions.csv':['reference','plus_activity','plus_hr_activity','context_without_glucose'],'personal_event_calibration/daily_predictions.csv':['reference_additive','reference_ratio','plus_hr_activity_additive','plus_hr_activity_ratio'],'matched_event_calibration/daily_predictions.csv':['clock','glucose','context','glucose_context'],'exact_event_probe/daily_predictions.csv':['clock','cgm','cgm_clock'],'expanded_event_probe/daily_predictions.csv':['clock','cgm','cgm_clock']}
for rel,cols in manifest.items():
 f=ROOT/rel;d=pd.read_csv(f);assert len(d)==44 and not d.duplicated(keys).any();z=truth.merge(d,on=keys,how='outer',validate='one_to_one',suffixes=('_truth',''));assert len(z)==44;assert np.array_equal(z.actual_truth,z.actual)
 for col in cols:
  assert np.isfinite(z[col]).all();e=abs(z[col]-z.actual)/z.actual*100;rows.append(dict(file=rel,prediction_column=col,n=44,mape=e.mean(),within10=int((e<=10).sum()),maximum_error_pct=e.max(),sha256=hashlib.sha256(f.read_bytes()).hexdigest()))
r=pd.DataFrame(rows);r.to_csv(OUT/'verified_results.csv',index=False);best=pd.read_csv(ROOT/'ensemble_probe/later_results.csv');best['error_pct']=100*abs(best.uniform-best.actual)/best.actual;best[best.error_pct>10][['pid','day','actual','uniform','error_pct']].to_csv(OUT/'reference_failures.csv',index=False)
s=dict(verified_prediction_vectors=len(r),prediction_vectors_mape_at_most10=int((r.mape<=10).sum()),prediction_vectors_all44_within10=int((r.within10==44).sum()),best_recorded_mape=float(r.mape.min()),best_reference_failed_days=int((best.error_pct>10).sum()),completion=False,requirements={'daily_grams':'evaluated against recorded daily labels','personalization':'historical known labels allowed; tested','passive_inputs':'strict reference uses sensors and calibration only','within10':'contradicted by current results','generalization':'44 later days repeatedly inspected; no independent confirmation','all_days_retained':'verified for all audited vectors'},additional_data=json.loads((ROOT/'additional_calibration_audit/summary.json').read_text()))
(OUT/'completion_audit.json').write_text(json.dumps(s,indent=2));print(json.dumps(s,indent=2))
